// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXYrW4BcWP0m9RGQehGD4uDX2rF69qco',
    appId: '1:458389339372:web:cafa0b34fa2c9ed4cdb9c9',
    messagingSenderId: '458389339372',
    projectId: 'studyspot-bc2fa',
    authDomain: 'studyspot-bc2fa.firebaseapp.com',
    storageBucket: 'studyspot-bc2fa.firebasestorage.app',
    measurementId: 'G-725Z306T90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACSM08VswP8Q-bEYjnBXAMa5TEfvn6-BU',
    appId: '1:458389339372:android:38d08ea0651ec572cdb9c9',
    messagingSenderId: '458389339372',
    projectId: 'studyspot-bc2fa',
    storageBucket: 'studyspot-bc2fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchdPj9ILkeRKmGm3rhediUfkLP-9fIO8',
    appId: '1:458389339372:ios:a804f64c5da33cb3cdb9c9',
    messagingSenderId: '458389339372',
    projectId: 'studyspot-bc2fa',
    storageBucket: 'studyspot-bc2fa.firebasestorage.app',
    iosBundleId: 'com.example.studyspot64',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchdPj9ILkeRKmGm3rhediUfkLP-9fIO8',
    appId: '1:458389339372:ios:a804f64c5da33cb3cdb9c9',
    messagingSenderId: '458389339372',
    projectId: 'studyspot-bc2fa',
    storageBucket: 'studyspot-bc2fa.firebasestorage.app',
    iosBundleId: 'com.example.studyspot64',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdXYrW4BcWP0m9RGQehGD4uDX2rF69qco',
    appId: '1:458389339372:web:8797b896ac983250cdb9c9',
    messagingSenderId: '458389339372',
    projectId: 'studyspot-bc2fa',
    authDomain: 'studyspot-bc2fa.firebaseapp.com',
    storageBucket: 'studyspot-bc2fa.firebasestorage.app',
    measurementId: 'G-JF5JVEMXDS',
  );
}
